//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by Property.rc
//
#define ID_APPLY                        3
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_PROPERTY_DIALOG             102
#define IDB_SPLASH                      103
#define IDD_PACKET_MONITOR              105
#define IDR_MAINFRAME                   128
#define IDD_LOG_QUERY                   131
#define IDI_PACKET_MONITOR              134
#define IDD_ACL                         137
#define IDD_SYSTEM_SET                  138
#define IDD_ABOUT                       139
#define IDD_DIALOG_ACL                  140
#define IDD_SET_NET                     141
#define IDD_SET_TIME                    142
#define IDD_NET_IP_ARIA                 145
#define IDD_DIALOG_REGISTER             146
#define IDD_DIALOG_REMOVE               147
#define IDI_ACL_MEMO                    154
#define IDI_ALERT_SET                   155
#define IDI_APP_SET                     156
#define IDI_BASE_SET                    157
#define IDI_COMMON_SET                  158
#define IDI_NET_SET                     161
#define IDI_SUPER_SET                   162
#define IDI_TIME_SET                    163
#define IDI_XFILTER                     164
#define IDI_IP_SET                      165
#define IDI_EMAIL                       166
#define IDI_LOG_QUERY_RESULT            167
#define IDI_LOG_QUERY_SET               168
#define IDI_REMOVE                      169
#define IDI_USER_INFO                   170
#define IDI_ACL_SET                     172
#define IDI_SMALL_MESSAGE               177
#define IDI_SMALL_NULL                  178
#define IDI_SMALL_ALERT                 180
#define IDI_SMALL_QUERY                 202
#define IDI_SMALL_PASS                  203
#define IDI_SMALL_DENY                  204
#define IDB_ABOUT                       209
#define IDC_BUTTON_SCROLL               1001
#define IDC_BUTTON_APPLICATION          1001
#define IDC_PACKET_MONITOR              1002
#define IDC_BUTTON_MONITOR              1003
#define IDC_PACKET_MONITOR2             1003
#define IDC_BUTTON_NET                  1003
#define IDC_BUTTON_TIME                 1004
#define IDC_BUTTON_CLEAR                1004
#define IDC_PACKET_MONITOR3             1005
#define IDC_PACKET_MONITOR_LABLE        1006
#define IDC_PACKET_MONITOR4             1006
#define IDC_LIST_PACKET_MONITOR         1007
#define IDC_ACL_BASE_SET_LABLE          1008
#define IDC_ACL_LIST                    1008
#define IDC_ABOUT_LABLE_COPYRIGHT1      1008
#define IDC_LOG_QUERY_SET_START_TIME_LABLE 1009
#define IDC_ACL_SUPER_SET_LABLE         1009
#define IDC_ABOUT_LABLE_COPYRIGHT2      1009
#define IDC_LOG_QUERY_SET_END_TIME_LABLE 1010
#define IDC_ACL_MEMO_LABLE              1010
#define IDC_ABOUT_LABLE_COPYRIGHT3      1010
#define IDC_START_DATE                  1011
#define IDC_ABOUT_LABLE_WARNING         1011
#define IDC_STOP_DATE                   1012
#define IDC_ABOUT_LABLE_ACCREDIT_TO     1012
#define IDC_ABOUT_LABLE_WEB_ADDRESS     1013
#define IDC_START_TIME                  1014
#define IDC_ABOUT_LABLE_EMAIL           1014
#define IDC_ABOUT_LABLE_WEB_ADDRESS_LABLE 1015
#define IDC_STOP_TIME                   1016
#define IDC_ABOUT_LABLE_EMAIL_LABLE     1016
#define IDC_LOG_QUERY_BUTTON_QUERY      1017
#define IDC_ABOUT_LABLE_INFO            1017
#define IDC_LOG_QUERY_RESULT_LABLE      1018
#define IDC_ACL_RADIO_PASS              1018
#define IDC_ABOUT_LABLE_AUTHOR          1018
#define IDC_LOG_QUERY_BUTTON_BACK       1019
#define IDC_ACL_RADIO_QUERY             1019
#define IDC_SYSTEM_SET_CHECK_LOG        1019
#define IDC_ABOUT_LABLE_AUTHOR2         1019
#define IDC_ABOUT_LABLE_COPYRIGHT       1019
#define IDC_LOG_QUERY_BUTTON_NEXT       1020
#define IDC_ACL_RADIO_DENY              1020
#define IDC_SYSTEM_SET_LIST_LOG_SIZE    1020
#define IDC_LOG_QUERY_BUTTON_DELETE     1021
#define IDC_COMBO_APPLICATION           1021
#define IDC_SYSTEM_SET_CHECK_AUTOSTART  1021
#define IDC_LOG_QUERY_RESULT_LIST_LABLE 1022
#define IDC_COMBO_REMOTE_NET            1022
#define IDC_ACL_BUTTON_EDIT             1022
#define IDC_SYSTEM_SET_CHECK_ALERT_PCSPEAKER 1022
#define IDC_COMBO_ACCESS_TIME           1023
#define IDC_ACL_BUTTON_DELETE           1023
#define IDC_SYSTEM_SET_CHECK_ALERT_DIALOG 1023
#define IDC_COMBO_ACTION                1024
#define IDC_SET_TIME_CHECK_THURSDAY     1024
#define IDC_SYSTEM_SET_CHECK_SPLASH     1024
#define IDC_COMBO_DIRECTION             1025
#define IDC_SET_TIME_CHECK_FRIDAY       1025
#define IDC_COMBO_SERVICE_TYPE          1026
#define IDC_SET_TIME_CHECK_SATURDAY     1026
#define IDC_EDIT_SERVICE_PORT           1027
#define IDC_EDIT_MEMO                   1028
#define IDC_ACL_BUTTON_ADD              1028
#define IDC_REG_EDIT_ID                 1028
#define IDC_SET_NET_TREE                1029
#define IDC_REG_EDIT_EMAIL              1029
#define IDC_LIST_LOG                    1030
#define IDC_REG_EDIT_ADDRESS            1030
#define IDC_LOG_QUERY_SET_LABLE         1031
#define IDC_ACL_APPLICATION_LABLE       1032
#define IDC_ACL_REMOTE_NET_LABLE        1033
#define IDC_ACL_ACCESS_TIME_LABLE       1034
#define IDC_ACL_ACTION_LABLE            1035
#define IDC_ACL_DERECTION_LABLE         1036
#define IDC_REG_LABEL_WEB_STATION       1036
#define IDC_ACL_SERVICE_TYPE_LABLE      1037
#define IDC_ACL_SERVICE_PORT_LABLE      1038
#define IDC_ACL_APPLICATION_SET_LABLE   1039
#define IDC_REG_LABEL_GENDER            1039
#define IDC_ACL_SET_LABLE               1040
#define IDC_REG_LABEL_ZIP               1040
#define IDC_SET_TIME_TREE               1041
#define IDC_REG_LABEL_ID_TYPE           1041
#define IDC_SET_TIME_WEEK_TIME_LABLE    1042
#define IDC_REG_LABEL_ID                1042
#define IDC_SET_TIME_CHECK_SUNDAY       1043
#define IDC_REG_LABEL_BIRTHDAY          1043
#define IDC_SET_TIME_CHECK_MONDAY       1044
#define IDC_REG_LABEL_METIER            1044
#define IDC_SET_TIME_CHECK_TUESDAY      1045
#define IDC_REG_LABEL_ADDRESS           1045
#define IDC_SET_TIME_CHECK_WEDNESDAY    1046
#define IDC_REG_LABEL_DUTY              1046
#define IDC_SET_TIME_BUTTON_ADD         1047
#define IDC_REG_LABEL_DEGREE            1047
#define IDC_SET_TIME_BUTTON_EDIT        1048
#define IDC_REG_LABEL_SALARY            1048
#define IDC_SET_TIME_BUTTON_DELETE      1049
#define IDC_REG_LABEL_INC               1049
#define IDC_SET_TIME_LIST               1050
#define IDC_REG_LABEL_QQ                1050
#define IDC_SET_NET_LABLE               1051
#define IDC_SET_NET_NET_LABLE           1052
#define IDC_SET_NET_BUTTON_ADD          1053
#define IDC_SET_NET_BUTTON_EDIT         1054
#define IDC_SET_NET_BUTTON_DELETE       1055
#define IDC_SET_NET_LIST                1056
#define IDC_NET_IP_ARIA_LABLE_END_IP    1056
#define IDC_SET_TIME_TIME_LABLE         1057
#define IDC_SYSTEM_SET_COMMON_SET_LABLE 1058
#define IDC_SYSTEM_SET_UNIT_LABLE       1059
#define IDC_SYSTEM_SET_ALERT_SET_LABLE  1060
#define IDC_ABOUT_LABLE_TITLE           1061
#define IDC_ABOUT_OLE_COPYRIGHT         1062
#define IDC_ABOUT_OLE_OTHER             1063
#define IDC_SET_NET_IPADDRESS_START     1066
#define IDC_SET_NET_IPADDRESS_START2    1067
#define IDC_SET_NET_IPADDRESS_END       1067
#define IDC_NET_IP_ARIA_IP_START        1067
#define IDC_NET_IP_ARIA_IP_END          1068
#define IDC_SET_TIME_TIME_START         1068
#define IDC_SET_TIME_TIME_END           1069
#define IDC_SET_TIME_LABLE_START_TIME   1071
#define IDC_SET_TIME_LABLE_END_TIME     1072
#define IDC_NET_IP_ARIA_LABLE           1073
#define IDC_NET_IP_ARIA_LABLE_START_IP  1074
#define IDC_REG_COMBO_GENDER            1080
#define IDC_REG_COMBO_ID_TYPE           1082
#define IDC_REG_TIME_BIRTHDAY           1083
#define IDC_REG_COMBO_METIER            1084
#define IDC_REG_COMBO_DEGREE            1086
#define IDC_REG_COMBO_SALARY            1087
#define IDC_REG_LABEL_NAME              1088
#define IDC_REG_LABEL_EMAIL             1089
#define IDC_REG_EDIT_NAME               1090
#define IDC_REG_LABEL_INFO_1            1091
#define IDC_REG_LABEL_INFO_2            1092
#define IDC_REG_EDIT_ZIP                1093
#define IDC_REMOVE_CHECK_LOG            1093
#define IDC_REG_EDIT_DUTY               1094
#define IDC_REMOVE_CHECK_MAIN           1094
#define IDC_REMOVE_CHECK_ACL            1095
#define IDC_REG_EDIT_INC                1095
#define IDC_REMOVE_LABEL_LOGO           1096
#define IDC_REG_EDIT_QQ                 1096
#define IDC_REMOVE_LABEL_INFO           1097
#define IDC_REG_LABEL_PASSWORD          1098
#define IDC_REG_LABEL_INFO_3            1100
#define ID_PACKET_MONITOR               32772
#define ID_LOG_QUERY                    32773
#define ID_ACL_SET                      32774
#define ID_SYSTEM_SET                   32775
#define ID_ABOUT                        32776
#define ID_STOP_FILTER                  32777
#define ID_START_FILTER                 32778
#define ID_CONTROL_FRAME                32779

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        212
#define _APS_NEXT_COMMAND_VALUE         32781
#define _APS_NEXT_CONTROL_VALUE         1101
#define _APS_NEXT_SYMED_VALUE           104
#endif
#endif
