//{{NO_DEPENDENCIES}}
// App Studio generated include file.
// Used by WSTERM.RC
//
#define IDR_MAINFRAME                   2
#define IDD_ABOUTBOX                    100
#define IDD_CONNECT                     102
#define IDC_HOSTNAME                    1000
#define IDC_PORT                        1001
#define ID_SOCKET_CONNECT               32771
#define ID_SOCKET_CLOSE                 32772
#define ID_VIEW_SOCKETNOTIFICATIONS     32773
#define ID_EDIT_CLEARBUFFER             32774
#define IDP_SOCKETS_INIT_FAILED         61204

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS

#define _APS_NEXT_RESOURCE_VALUE        104
#define _APS_NEXT_COMMAND_VALUE         32775
#define _APS_NEXT_CONTROL_VALUE         1003
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
