//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by FTPServer.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDI_FTPSERVER                   100
#define IDS_ABOUTBOX                    101
#define IDD_APPLICATION                 102
#define IDP_SOCKETS_INIT_FAILED         103
#define IDD_USERS                       107
#define IDD_USERACCOUNTS                108
#define IDR_POPUP_MENU                  130
#define IDR_MAINMENU                    131
#define IDD_ADD_USER                    134
#define IDB_BANNER                      143
#define IDB_WATERMARK                   144
#define IDR_TOOLBAR1                    146
#define IDR_INFOBARMENU                 148
#define IDD_ABOUT                       149
#define IDI_USER                        150
#define IDR_TRACE_MENU                  151
#define IDI_STATISTICS                  153
#define IDR_IP_MENU                     154
#define IDR_ONLINE_MENU                 155
#define IDD_PROPPAGE_SECURITY           156
#define IDI_CONFIGURATION               157
#define IDD_ADD_IP                      159
#define IDR_TOOLBAR                     160
#define IDB_TOOLBARCOLOR                162
#define IDB_TOOLBARDISABLE              163
#define IDB_TOOLBARHOT                  164
#define IDI_LOG                         201
#define IDI_USERS                       202
#define IDI_ONLINE_USERS                202
#define IDD_PROPPAGE_ONLINE             203
#define IDD_PROPPAGE_CONFIGURATION      204
#define IDD_PROPPAGE_TRACE              205
#define IDD_PROPPAGE_STATISTICS         206
#define IDI_SECURITY                    207
#define IDD_ADD_USERINFO                207
#define IDI_LED_RED                     208
#define IDI_LED_OFF                     209
#define IDI_LED_GREEN                   210
#define IDI_NONE                        211
#define IDI_HOME                        212
#define IDC_TRACE                       1000
#define IDC_ONLINE_USERS                1001
#define IDC_DIR_LIST                    1003
#define IDC_DIALOG_AREA                 1003
#define IDC_FILES_READ                  1005
#define IDC_FILES_WRITE                 1006
#define IDC_FILES_DELETE                1007
#define IDC_FILES_APPEND                1008
#define IDC_DIRS_CREATE                 1009
#define IDC_DIRS_DELETE                 1010
#define IDC_DIRS_LIST                   1011
#define IDC_DIRS_SUBDIRS                1012
#define IDC_PASSWORD                    1013
#define IDC_ANONYMOUS                   1013
#define IDC_USER_LIST                   1016
#define IDC_ADD_USER                    1017
#define IDC_ADD_DIR                     1018
#define IDC_USERNAME                    1018
#define IDC_BROWSE                      1019
#define IDC_PROFILENAME                 1019
#define IDC_ACCOUNTNAME                 1019
#define IDC_LNK                         1020
#define IDC_PATH                        1020
#define IDC_RESOLVE_LINKS               1020
#define IDC_HOSTNAME                    1020
#define IDC_RELATIVE                    1021
#define IDC_CONFIRMPASSWORD             1021
#define IDC_EDIT_DIR                    1022
#define IDC_LOCALFOLDER                 1022
#define IDC_SET_HOME                    1023
#define IDC_DEL_DIR                     1024
#define IDC_CONNECTNOW                  1024
#define IDC_EDIT_USER                   1027
#define IDC_NAME                        1028
#define IDC_DEL_USER                    1029
#define IDC_DISABLE_ACCOUNT             1030
#define IDC_OUTLOOKBAR                  1031
#define IDC_USERS                       1032
#define IDC_PORT                        1033
#define IDC_LAUNCH_ON_STARTUP           1034
#define IDC_START_IN_TRAY               1035
#define IDC_MAX_USERS                   1036
#define IDC_TIMEOUT                     1037
#define IDC_WELCOME_MSG                 1038
#define IDC_GOODBYE_MSG                 1040
#define IDC_AUTOACTIVATE                1043
#define IDC_STATIC1                     1044
#define IDC_STARWARS                    1046
#define IDC_VIRTUALDIR                  1046
#define IDC_ALIAS                       1047
#define IDC_STATIC2                     1048
#define IDC_STATIC3                     1049
#define IDC_DOWNLOAD                    1053
#define IDC_UPLOAD                      1054
#define IDC_RENAME                      1055
#define IDC_DELETE                      1056
#define IDC_CREATE_DIR                  1057
#define IDC_VIEW                        1058
#define IDC_CLEAR                       1059
#define IDC_APPLY                       1060
#define IDC_STATISTICS                  1062
#define IDC_IPLIST                      1064
#define IDC_LIST1                       1065
#define IDC_BLOCKEDLIST                 1065
#define IDC_USERSLIST                   1065
#define IDC_ADD                         1066
#define IDC_ADD_BLOCK                   1066
#define IDC_BUTTON2                     1067
#define IDC_REMOVE_BLOCK                1067
#define IDC_EDIT                        1068
#define IDC_EDIT_BLOCK                  1068
#define IDC_LIST2                       1069
#define IDC_NONBLOCKEDLIST              1069
#define IDC_BLOCK_ALL                   1070
#define IDC_ADD2                        1071
#define IDC_ADD_NONBLOCK                1071
#define IDC_IPADDRESS                   1071
#define IDC_BUTTON3                     1072
#define IDC_REMOVE_NONBLOCK             1072
#define IDC_EDIT2                       1073
#define IDC_EDIT_NONBLOCK               1073
#define IDC_IPADDRESS1                  1074
#define IDC_IPADDRESS2                  1075
#define IDC_HOMEDIRECTORY               1075
#define IDC_WIZARD                      1076
#define IDC_APPLICATIONNAME             1077
#define IDC_BTN_SERVERLOG               1078
#define IDC_BTN_ONLINEUSERS             1079
#define IDC_EDIT1                       1079
#define IDC_EDIT_USERNAME               1079
#define IDC_BTN_CONFIGURATION           1080
#define IDC_EDIT3                       1080
#define IDC_EDIT_USERPASS               1080
#define IDC_BTNADDUSERACCOUNT           1080
#define IDC_BTN_STATISTICS              1081
#define IDC_EDIT4                       1081
#define IDC_EDIT_USERPASSAGAIN          1081
#define IDC_BTNEDITUSERACCOUNT          1081
#define IDC_BTN_SECURITY                1082
#define IDC_BTNEDELUSERACCOUNT          1082
#define IDC_LOGLEVEL                    2014
#define ID_APP_SHOW                     32771
#define ID_SERVER_START                 32772
#define ID_SERVER_STOP                  32773
#define ID_SERVER_EXIT                  32774
#define ID_HELP_ABOUT                   32775
#define ID_USER_ACCOUNTS                32776
#define ID_BUTTON32779                  32779
#define IDC_VIEW_TRACE                  32783
#define IDC_VIEW_ONLINE_USERS           32784
#define IDC_VIEW_CONFIGURATION          32785
#define IDC_ABOUT                       32786
#define ID_TRACE_CLEAR                  32787
#define IDC_COPYIP                      32789
#define IDC_KICK_USER                   32790
#define IDC_CHANGE_RIGHTS               32791
#define IDC_BLOCK_IP                    32792
#define IDC_VIEW_STATISTICS             32793
#define IDC_VIEW_SECURITY               32794
#define ID_ACCOUNT_WIZARD               32796
#define ID_BUTTON32798                  32798
#define ID_BUTTON32800                  32800
#define ID_BUTTON32801                  32801
#define ID_BUTTON32802                  32802
#define ID_BUTTON32803                  32803
#define ID_BUTTON32804                  32804
#define ID_BUTTON32805                  32805
#define ID_ABOUT                        32807
#define ID_TRACEPAGE                    32808
#define ID_VIEW_ONLINEUSERS             32809
#define ID_VIEW_STATISTICS              32810
#define ID_VIEW_CONFIGURATION           32811
#define IDS_ADDUSERDIALOG               61204
#define IDS_ERRORMSG_ENTERSTRING        61205
#define IDS_BROWSEFORFOLDER             61206
#define IDS_OPTIONSPAGE_GENERAL         61207
#define IDS_OPTIONSPAGE_SECURITY        61208
#define IDS_INPUTDIALOGTEXT_RENAME      61209
#define IDS_ERRORMSG_USERALREADYEXISTS  61210
#define IDS_OPTIONSPAGE_MISC            61211
#define ID_INDICATOR_TIME               61212
#define ID_INDICATOR_DATA_RECEIVED      61212
#define ID_INDICATOR_ONLINELED          61213
#define ID_INDICATOR_OFFLINELED         61214
#define ID_INDICATOR_DATA_SEND          61215
#define IDS_HEADERTITLE1                61449
#define IDS_HEADERTITLE2                61450
#define IDS_HEADERTITLE3                61451
#define IDS_HEADERTITLE4                61452

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        169
#define _APS_NEXT_COMMAND_VALUE         32812
#define _APS_NEXT_CONTROL_VALUE         1082
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
