//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by Afd.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDM_SHOW                        0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_AFD_DIALOG                  102
#define IDS_RASCS_1                     102
#define IDS_RASCS_2                     103
#define IDS_RASCS_3                     104
#define IDS_RASCS_4                     105
#define IDS_RASCS_5                     106
#define IDS_RASCS_6                     107
#define IDS_RASCS_7                     108
#define IDS_RASCS_8                     109
#define IDS_RASCS_9                     110
#define IDS_RASCS_10                    111
#define IDS_RASCS_11                    112
#define IDS_RASCS_12                    113
#define IDS_RASCS_13                    114
#define IDS_RASCS_14                    115
#define IDS_RASCS_15                    116
#define IDS_RASCS_16                    117
#define IDS_RASCS_17                    118
#define IDS_RASCS_18                    119
#define IDS_RASCS_19                    120
#define IDS_RASCS_20                    121
#define IDS_RASCS_21                    122
#define IDS_RASCS_22                    123
#define IDS_RASCS_23                    124
#define IDS_RASCS_24                    125
#define IDS_RASCS_25                    126
#define IDS_RASCS_26                    127
#define IDR_MAINFRAME                   128
#define IDS_RASCS_27                    128
#define IDS_LIST1_COL1                  128
#define IDD_DIALOG1                     129
#define IDS_LIST1_COL2                  129
#define IDD_DIALOG2                     130
#define IDS_LOST_OF_CARRIER             130
#define IDD_DIALOG3                     131
#define IDS_TIME_OUT                    131
#define IDD_DIALOG4                     132
#define IDS_TERMINATING_CONN            132
#define IDD_DIALOG5                     133
#define IDS_PAUSE                       133
#define IDB_MORDA                       134
#define IDS_ONLINE                      134
#define IDD_PHONE_NUMBER                135
#define IDS_EXTERN_ONLINE               135
#define IDB_BGROUND5                    136
#define IDS_DELETE_CONNECTION           136
#define IDR_MIDIFILE1                   137
#define IDS_DELETE_PHONE                137
#define IDS_DELETE_PROGRAM              138
#define IDR_TRAY_MENU1                  139
#define IDS_ARG_HELP                    139
#define IDD_RUN_PROGRAM                 140
#define IDS_LIST2_COL1                  140
#define IDS_LIST2_COL2                  141
#define IDB_PHILOSOPHICAL_GNU           141
#define IDS_DISCONNECT_LOW_TRAFFIC      142
#define IDS_DIAL                        143
#define IDS_HANGUP                      144
#define IDS_LAST_UPDATES                145
#define IDS_JOIN_MAIL_LIST              146
#define IDS_SRC_INFO                    147
#define IDC_FRAME                       1000
#define IDC_CHECK1                      1001
#define IDC_CHECK_TIMEOUT               1001
#define IDC_HIDEPWD                     1001
#define IDC_CHECK2                      1002
#define IDC_CHECK_SPEED                 1002
#define IDC_CHECK3                      1003
#define IDC_CHECK_PING                  1003
#define IDC_CHECK4                      1004
#define IDC_CHECK_TERMINATE             1004
#define IDC_CHECK5                      1005
#define IDC_CHECK_REDIAL                1005
#define IDC_CHECK6                      1006
#define IDC_CHECK_HANGUP                1006
#define IDC_CHECK7                      1007
#define IDC_CHECK_LOG                   1007
#define IDC_CHECK8                      1008
#define IDC_CHECK_INTERFACE_START_MINIMIZED 1008
#define IDC_CHECK9                      1009
#define IDC_CHECK_INTERFACE_START_MINIMIZED2 1009
#define IDC_CHECK10                     1010
#define IDC_COMBO_PROVIDER              1011
#define IDC_BUTTON_PROV_ADD             1012
#define IDC_BUTTON_PROV_EDIT            1013
#define IDC_BUTTON_PROV_DEL             1014
#define IDC_LIST_PHONES                 1015
#define IDC_BUTTON_TEL_ADD              1016
#define IDC_BUTTON_TEL_EDIT             1017
#define IDC_BUTTON_TEL_DEL              1018
#define IDC_DIAL                        1019
#define IDC_PROGRESS_TIMEOUT            1020
#define IDC_STATUS                      1021
#define IDC_LAST_CALL                   1022
#define IDC_STATIC_NAME                 1023
#define IDC_EDIT_USER_NAME              1024
#define IDC_EDIT_PASSWORD               1025
#define IDC_EDIT_SOUND_LOGIN            1026
#define IDC_LOAD_LOGIN                  1028
#define IDC_LOAD_LOGOUT                 1029
#define IDC_EDIT_TIME_CUR               1029
#define IDC_TEST_LOGIN                  1030
#define IDC_RADIO1                      1030
#define IDC_EDIT_TIME_TOT               1030
#define IDC_EDIT_PROGRAM_01             1031
#define IDC_RADIO2                      1031
#define IDC_TEST_LOGOUT                 1032
#define IDC_EDIT_RECV                   1032
#define IDC_RADIO3                      1032
#define IDC_LOAD_PROGRAM_01             1033
#define IDC_EDIT_SENT                   1033
#define IDC_EDIT_SOUND_LOGOUT           1034
#define IDC_EDIT_TERMTIME               1035
#define IDC_CLEAN                       1036
#define IDC_BUTTON_VEW_LOG              1037
#define IDC_EDIT_LOG                    1038
#define IDC_STATIC_PANEL                1039
#define IDC_STATIC_VERSION              1040
#define IDC_STATIC_HOMEPAGE             1041
#define IDC_STATIC_MAIL                 1042
#define IDC_EDIT_MAIL                   1043
#define IDC_BUTTON_MAIL                 1044
#define IDC_EDIT_TIMEOUT                1045
#define IDC_STATIC_HOMEPAGE2            1045
#define IDC_EDIT_SPEED                  1046
#define IDC_STATIC_SRC                  1046
#define IDC_EDIT_PING                   1047
#define IDC_EDIT_TERMINATE              1048
#define IDC_BUTTON_FILE_LOG             1049
#define IDC_EDIT1                       1050
#define IDC_EDIT2                       1051
#define IDC_HIDE                        1052
#define IDC_LIST_PROGS                  1053
#define IDC_BUTTON_PROG_ADD             1054
#define IDC_BUTTON_PROG_EDIT            1055
#define IDC_BUTTON_PROG_DEL             1056
#define IDC_LOAD                        1057
#define IDC_EDIT_NAME                   1059
#define IDC_FACE_FRAME                  1061
#define IDC_BUTTON_DIAL                 1062
#define IDC_BUTTON2                     1064
#define IDC_BUTTON4                     1066
#define IDM_TRAY_DIAL                   32771

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        142
#define _APS_NEXT_COMMAND_VALUE         32772
#define _APS_NEXT_CONTROL_VALUE         1067
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
